name: gpflow6_0
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - xarray=0.14.0
  - xesmf
  - scipy
  - matplotlib
  - cartopy
  - python=3.6
  - pip
  - netcdf4
  - dask
  - jupyterlab

- pip:
    - df2gspread
    - oauth2client
    - gspread
    - tensorflow==2.1.0
    - gpflow==2.0.0
    # - git+https://github.com/GPflow/GPflow.git@develop#egg=gpflow
  #   - git+https://github.com/GPflow/GPflowOpt.git#egg=gpflowopt


